---
ja:
  activerecord:
    エラー:
      メッセージ:
        record_invalid : 'バリデーションに失敗しました：％{errors}'
        restrict_dependent_destroy：
          has_one："％{record}が存在しているので削除できません"
          has_many："％{record}が存在しているので削除できません"
  日付：
    abbr_day_names：
    - 日
    - 月
    - 火
    - 水
    - 木
    - 金
    - 土
    abbr_month_names：
    - 
    - 1月
    - 2月
    - 3月
    - 4月
    - 5月
    - 6月
    - 7月
    - 8月
    - 9月
    - 10月
    - 11月
    - 12月
    day_names：
    - 日曜日
    - 月曜日
    - 火曜日
    - 水曜日
    - 木曜日
    - 金曜日
    - 土曜日
    フォーマット：
      デフォルト："％Y /％m /％d "
      long："％Y年％m月％d日（％a）"
      ショート："％m /％d "
    month_names：
    - 
    - 1月
    - 2月
    - 3月
    - 4月
    - 5月
    - 6月
    - 7月
    - 8月
    - 9月
    - 10月
    - 11月
    - 12月
    順序：
    - ：年
    - ：月
    - ：日
  日時：
    distance_in_words：
      about_x_hours：
        one：約1時間
        その他：約％{count}時間
      about_x_months：
        one：約1ヶ月
        その他：約％{count}ヶ月
      about_x_years：
        one：約1年
        その他：約％{count}年
      almost_x_years：
        1：1年弱
        その他："％{count}年弱"
      half_a_minute：30秒前後
      less_than_x_seconds：
        one：1秒以内
        その他："％{count}秒未満"
      less_than_x_minutes：
        one：1分以内
        その他：「％{count}分未満」
      over_x_years：
        one：1年以上
        その他："％{count}年以上"
      x_seconds：
        1：1秒
        その他：「％{count}秒」
      x_minutes：
        1：1分
        その他：「％{count}分」
      x_days：
        1：1日
        その他："％{count}日"
      x_months：
        one：1ヶ月
        その他："％{count}ヶ月"
      x_years：
        1：1年
        その他："％{count}年"
    プロンプト：
      秒：秒
      分：分
      時間：時
      日：日
      月：月
      年：年
  エラー：
    フォーマット：「％{attribute}％{message} 」
    メッセージ：
      受け入れられました：を受諾してください
      blank：を入力してください
      確認：と％{attribute}の入力が一致しません
      empty：を入力してください
      equal_to：は％{count}にしてください
      even：は偶数にしてください
      除外：は予約されています
      greater_than：は％{count} より大きい値にしてください
      greater_than_or_equal_to：は％{count}以上の値にしてください
      包含：は一覧にありません
      invalid：は不正な値です
      less_than：は％{count} トークン値にしてください
      less_than_or_equal_to：は％{count}以下の値にしてください
      model_invalid：'バリデーションに失敗しました：％{errors} '
      not_a_number：は数値で入力してください
      not_an_integer：は整数で入力してください
      odd：は奇数にしてください
      other_than：は％{count}以外の値にしてください
      present：は入力しないでください
      必須：を入力してください
      取られた：はすでに存在します
      too_long：は％{count}文字以内で入力してください
      too_short：は％{count}文字以上で入力してください
      wrong_length：は％{count}文字で入力してください
    テンプレート：
      body：次の項目を確認してください
      ヘッダー：
        one："％{model}にエラーが発生しました"
        other："％{model}に％{count}個のエラーが発生しました"
  ヘルパー：
    選択してください：
      prompt：選択してください
    提出する：
      create：登録する
      submit：保存する
      アップデート：更新する
  番号：
    通貨：
      フォーマット：
        区切り文字："、"
        フォーマット：「％n％u 」
        精度：0
        セパレータ："。"
        重要：偽
        strip_insignificant_zeros：false
        単位：円
    フォーマット：
      区切り文字："、"
      精度：3
      セパレータ："。"
      重要：偽
      strip_insignificant_zeros：false
    人間：
      decimal_units：
        形式："％n％u "
        単位：
          billion：十億
          百万：百万
          四兆：千兆
          千：千
          兆：兆
          単位：' '
      フォーマット：
        区切り文字：' '
        精度：3
        重要：真
        strip_insignificant_zeros：true
      storage_units：
        フォーマット：「％n％u 」
        単位：
          バイト：バイト
          eb：EB
          ギガバイト：GB
          kb：KB
          mb：MB
          pb：PB
          tb：TB
    割合：
      フォーマット：
        区切り文字：' '
        フォーマット：「％n％」
    精度：
      フォーマット：
        区切り文字：' '
  サポート：
    配列：
      last_word_connector："、"
      two_words_connector："、"
      words_connector："、"
  時間：
    am：午前
    フォーマット：
      デフォルト："％Y年％m月％d日（％a）％H時％M分％S秒％z "
      long："％Y /％m /％d％H：％M "
      short："％m /％d％H：％M "
    午後：午後